"""initial CareSignal schema

Revision ID: 996314bc3c24
Revises:
Create Date: 2026-07-17 20:19:14.205904
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "996314bc3c24"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "patient",
                "clinician",
                "demo_admin",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "preferred_language",
            sa.Enum(
                "en",
                "sn",
                "nd",
                "mixed",
                "unknown",
                name="language",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "clinician_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("display_role", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_clinician_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinician_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_clinician_profiles_user_id")),
    )
    op.create_table(
        "patient_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("synthetic_identifier", sa.String(length=40), nullable=False),
        sa.Column(
            "preferred_channel",
            sa.Enum(
                "app",
                "whatsapp_simulator",
                "whatsapp_sandbox",
                name="channel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("consent_demo_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_patient_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_profiles")),
        sa.UniqueConstraint(
            "synthetic_identifier", name=op.f("uq_patient_profiles_synthetic_identifier")
        ),
        sa.UniqueConstraint("user_id", name=op.f("uq_patient_profiles_user_id")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("patient_id", sa.String(length=36), nullable=True),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_audit_events_patient_id_patient_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_table(
        "reading_submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "app",
                "whatsapp_simulator",
                "whatsapp_sandbox",
                name="submission_channel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("original_message", sa.Text(), nullable=True),
        sa.Column("candidate_payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_confirmation",
                "confirmed",
                "evaluated",
                "corrected",
                "rejected",
                "cancelled",
                name="submission_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.Enum(
                "en",
                "sn",
                "nd",
                "mixed",
                "unknown",
                name="submission_language",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_request_id", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_reading_submissions_patient_id_patient_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_submissions")),
    )
    op.create_table(
        "blood_pressure_readings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("systolic", sa.Integer(), nullable=False),
        sa.Column("diastolic", sa.Integer(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "medication_taken",
            sa.Enum(
                "yes",
                "no",
                "unknown",
                "prefer_not_to_say",
                name="medication_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("missed_medication_reason_code", sa.String(length=80), nullable=True),
        sa.Column("context_codes", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_blood_pressure_readings_patient_id_patient_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["reading_submissions.id"],
            name=op.f("fk_blood_pressure_readings_submission_id_reading_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blood_pressure_readings")),
        sa.UniqueConstraint("submission_id", name=op.f("uq_blood_pressure_readings_submission_id")),
    )
    op.create_table(
        "rule_evaluations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("reading_id", sa.String(length=36), nullable=False),
        sa.Column("rule_id", sa.String(length=100), nullable=False),
        sa.Column("rule_version", sa.String(length=40), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "routine",
                "watch",
                "needs_review",
                "urgent_review",
                name="task_priority",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("source_reference", sa.String(length=255), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_rule_evaluations_patient_id_patient_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"],
            ["blood_pressure_readings.id"],
            name=op.f("fk_rule_evaluations_reading_id_blood_pressure_readings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_evaluations")),
    )
    op.create_table(
        "review_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "routine",
                "watch",
                "needs_review",
                "urgent_review",
                name="review_task_priority",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "assigned",
                "in_review",
                "resolved",
                name="task_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("assigned_clinician_id", sa.String(length=36), nullable=True),
        sa.Column("primary_rule_evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome_code", sa.String(length=80), nullable=True),
        sa.Column("outcome_note", sa.Text(), nullable=True),
        sa.Column("reopened_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_clinician_id"],
            ["clinician_profiles.id"],
            name=op.f("fk_review_tasks_assigned_clinician_id_clinician_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_review_tasks_patient_id_patient_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["primary_rule_evaluation_id"],
            ["rule_evaluations.id"],
            name=op.f("fk_review_tasks_primary_rule_evaluation_id_rule_evaluations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_tasks")),
    )
    op.create_table(
        "contact_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("clinician_id", sa.String(length=36), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "app",
                "whatsapp_simulator",
                "whatsapp_sandbox",
                name="contact_channel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("outcome_code", sa.String(length=80), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["clinician_profiles.id"],
            name=op.f("fk_contact_attempts_clinician_id_clinician_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["review_tasks.id"], name=op.f("fk_contact_attempts_task_id_review_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_attempts")),
    )
    op.create_table(
        "patient_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column(
            "direction",
            sa.Enum(
                "inbound",
                "outbound",
                name="message_direction",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "app",
                "whatsapp_simulator",
                "whatsapp_sandbox",
                name="message_channel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.Enum(
                "en",
                "sn",
                "nd",
                "mixed",
                "unknown",
                name="message_language",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "generation_type",
            sa.Enum(
                "fixed_template",
                "ai_draft",
                "clinician_authored",
                name="generation_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "approval_status",
            sa.Enum(
                "draft",
                "approved",
                "sent",
                "rejected",
                name="approval_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "delivery_status",
            sa.Enum(
                "not_sent",
                "sent",
                "delivered",
                "delivery_failed",
                name="delivery_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_patient_messages_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_patient_messages_patient_id_patient_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["review_tasks.id"], name=op.f("fk_patient_messages_task_id_review_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_messages")),
    )
    op.create_table(
        "task_evidence",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("rule_evaluation_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_evaluation_id"],
            ["rule_evaluations.id"],
            name=op.f("fk_task_evidence_rule_evaluation_id_rule_evaluations"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["review_tasks.id"], name=op.f("fk_task_evidence_task_id_review_tasks")
        ),
        sa.PrimaryKeyConstraint("task_id", "rule_evaluation_id", name=op.f("pk_task_evidence")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_evidence")
    op.drop_table("patient_messages")
    op.drop_table("contact_attempts")
    op.drop_table("review_tasks")
    op.drop_table("rule_evaluations")
    op.drop_table("blood_pressure_readings")
    op.drop_table("reading_submissions")
    op.drop_table("audit_events")
    op.drop_table("patient_profiles")
    op.drop_table("clinician_profiles")
    op.drop_table("users")
    # ### end Alembic commands ###
